service: aws-node-http-api-project
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - 'dynamoDB:PutItem'
            - 'dynamoDB:UpdateItem'
            - 'dynamoDB:GetItem'
            - 'dynamoDB:Scan'
          Resource:
            - arn:aws:dynamodb:us-east-1:942441947374:table/ItemTableNew

functions:
  hello:
    handler: src/handler.hello
    events:
      - httpApi:
          path: /
          method: get
  insertItem:
    handler: src/insertItem.handler
    events:
      - httpApi:
          path: /item
          method: post
  fetchItems:
    handler: src/fetchItems.handler
    events:
      - httpApi:
          path: /items
          method: get
  fetchItem:
    handler: src/fetchItem.handler
    events:
      - httpApi:
          path: /item/{id}
          method: get
  updateItem:
    handler: src/updateItem.handler
    events:
      - httpApi:
          path: /items/{id}
          method: put


resources:
  Resources:
    ItemTableNew:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ItemTableNew
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH

